apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/mongo/data/db"
    type: DirectoryOrCreate
