kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.5-jessie
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: mongodb
                operator: In
                values:
                - "true"
      volumes:
      - name: mongodb-persistent-storage
        # Put a pointer here instead of manually configuring the which type of volume to use on a deployment level
        # This is to allow the volume to be configured at the cluster level
        # hostPath:
        #   path: /mnt/data/db
        #   type: DirectoryOrCreate
        persistentVolumeClaim:
          claimName: mongo-pvc

--- 
kind: Service
apiVersion: v1
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
  - name: mongoport
    port: 27017
  type: ClusterIP
