apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-ssd
  resources:
    requests:
      storage: 10Gi

--- 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-ssd
provisioner: ebs.csi.aws.com
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp2  
  